{
  "name": "stubbox",
  "version": "1.0.0",
  "description": "Stub BoxOffice, a resale ticketing site",
  "main": "app.js",
  "scripts": {
    "production": "npm run production:admin && npm run production:start",
    "production:admin": "cd admin/ && pm2 start ./bin/www -n Admin",
    "production:start": "pm2 start ecosystem.config.js",
    "production:stop": "pm2 delete all",
    "production:restart": "npm run production:stop && npm run production:start",
    "dev": "npm-run-all -p start-dev:*",
    "start-dev:admin": "cd admin/ && nodemon ./bin/www",
    "start-dev:scss": "npm-run-all -p scss:*",
    "start-dev:server": "nodemon app.js",
    "start-admin": "nodemon ../StubAdmin/bin/www",
    "scss:watch": "chokidar 'assets/src/scss/**/*.scss' -c 'npm run scss:build'",
    "scss:build": "npm-run-all -p build-task:*",
    "build-task:scss-compile": "node-sass --source-map true assets/src/scss/ -o assets/dist/css",
    "build-task:autoprefixer": "postcss assets/dist/css/*.css --use autoprefixer -d assets/dist/css"
  },
  "author": "two words LLC",
  "license": "ISC",
  "dependencies": {
    "@sendgrid/mail": "^6.5.5",
    "axios": "^0.18.1",
    "body-parser": "^1.20.0",
    "bot-detector": "^1.0.10",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "csv-parser": "^2.3.5",
    "debug": "^4.3.4",
    "dotenv": "^7.0.0",
    "easy-soap-request": "^2.6.0",
    "ejs": "^2.7.4",
    "express": "^4.18.1",
    "express-sanitizer": "^1.0.6",
    "helmet": "^3.23.3",
    "knex": "^0.16.5",
    "lodash": "^4.17.21",
    "mysql": "^2.18.1",
    "node-fetch": "^2.3.0",
    "pm2": "^3.5.2",
    "rapidx2j": "^0.5.1",
    "redis": "^2.8.0",
    "slug": "^1.1.0",
    "winston": "^3.8.2",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "autoprefixer": "^9.8.8",
    "chokidar-cli": "^1.2.3",
    "node-sass-chokidar": "^1.5.0",
    "nodemon": "^1.19.4",
    "npm-run-all": "^4.1.5",
    "postcss-cli": "^6.1.3"
  }
}
